on:
  pull_request:
    branches:
      - master
    paths:
      - '**.py'
      - '**.yml'
      - 'test_template.txt'
jobs:
  statshouse-client-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: go run github.com/vkcom/statshouse/cmd/statshouse-client-test@master
